export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;

export const ERROR_CODES = {
  AUTHENTICATION_FAILED: 'AUTH_001',
  TOKEN_EXPIRED: 'AUTH_002',
  TOKEN_INVALID: 'AUTH_003',
  INSUFFICIENT_PERMISSIONS: 'AUTH_004',
  BLUEPRINT_NOT_FOUND: 'BP_001',
  BLUEPRINT_INVALID: 'BP_002',
  BLUEPRINT_CONFLICT: 'BP_003',
  WORKSPACE_NOT_FOUND: 'WS_001',
  WORKSPACE_INVALID: 'WS_002',
  AGENT_NOT_FOUND: 'AGT_001',
  AGENT_INVALID: 'AGT_002',
  DAG_INVALID: 'DAG_001',
  DAG_CYCLE_DETECTED: 'DAG_002',
  SCRIPT_EXECUTION_FAILED: 'SCR_001',
  SCRIPT_TIMEOUT: 'SCR_002',
  CONTRACT_INVALID: 'CTR_001',
  MEMORY_NOT_FOUND: 'MEM_001',
  GIT_OPERATION_FAILED: 'GIT_001',
  GIT_CONFLICT: 'GIT_002',
  SANDBOX_ERROR: 'SBX_001',
  AI_SERVICE_ERROR: 'AI_001',
  DATABASE_ERROR: 'DB_001',
  VALIDATION_ERROR: 'VAL_001',
  INTERNAL_ERROR: 'INT_001',
} as const;

export const ROLES = {
  ADMIN: 'admin',
  EDITOR: 'editor',
  VIEWER: 'viewer',
} as const;

export const AUTH_HEADER = 'authorization';
export const AUTH_HEADER_PREFIX = 'Bearer ';
export const DEFAULT_PAGE_SIZE = 20;
export const MAX_PAGE_SIZE = 100;
